/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BorsaWorker;
import controller.MumGrafikYonetici;
import controller.ComboBoxYonetici;
import controller.KriptoParaYonetici;
import java.awt.event.ItemEvent;
import javax.swing.SwingWorker;
import model.KriptoPara;
import model.KriptoParaBorsaBilgi;

/**
 *
 * @author asimsinanyuksel
 */
public class KriptoParaDurumuFrame extends javax.swing.JFrame {
    
    private KriptoParaYonetici hdc;
    private ComboBoxYonetici cby;
    private MumGrafikYonetici mgy;

    /**
     * Creates new form HavaDurumuFrame
     */
    public KriptoParaDurumuFrame() {
        initComponents();
        hdc=new KriptoParaYonetici();
        cby=new ComboBoxYonetici(paralarListe);
        mgy=new MumGrafikYonetici(mumPanel);
        new BorsaWorker(hdc, mgy, cby, durumLabel)
        .execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kriptoParaDurumPanel = new javax.swing.JPanel();
        sembolPanel = new javax.swing.JPanel();
        sembolIconLabel = new javax.swing.JLabel();
        sembolMetinLabel = new javax.swing.JLabel();
        borsaBilgiPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fiyatDegisikligiLabel = new javax.swing.JLabel();
        fiyatDegisikligiYuzdeLabel = new javax.swing.JLabel();
        sonFiyatLabel = new javax.swing.JLabel();
        enDusukFiyatLabel = new javax.swing.JLabel();
        enYuksekFiyatLabel = new javax.swing.JLabel();
        hacimLabel = new javax.swing.JLabel();
        paralarListe = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        mumPanel = new javax.swing.JPanel();
        durumLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kripto Para Bilgileri");

        kriptoParaDurumPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kripto Para Bilgileri", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        kriptoParaDurumPanel.setLayout(new java.awt.GridLayout(1, 0));

        sembolPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sembol", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        sembolIconLabel.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        sembolIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sembolIconLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        sembolMetinLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        sembolMetinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sembolMetinLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout sembolPanelLayout = new javax.swing.GroupLayout(sembolPanel);
        sembolPanel.setLayout(sembolPanelLayout);
        sembolPanelLayout.setHorizontalGroup(
            sembolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sembolMetinLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
            .addGroup(sembolPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(sembolIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sembolPanelLayout.setVerticalGroup(
            sembolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sembolPanelLayout.createSequentialGroup()
                .addComponent(sembolIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sembolMetinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
        );

        kriptoParaDurumPanel.add(sembolPanel);

        borsaBilgiPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Borsa Hareketleri", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Fiyat Değişikliği:");

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Fiyat Değişikliği (%):");

        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Son Fiyat:");

        jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("En Düşük Fiyat:");

        jLabel9.setFont(jLabel9.getFont().deriveFont(jLabel9.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("En Yüksek Fiyat:");

        jLabel10.setFont(jLabel10.getFont().deriveFont(jLabel10.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Hacim:");

        fiyatDegisikligiLabel.setText("0");

        fiyatDegisikligiYuzdeLabel.setText("0");

        sonFiyatLabel.setText("0");

        enDusukFiyatLabel.setText("0");

        enYuksekFiyatLabel.setText("0");

        hacimLabel.setText("0");

        javax.swing.GroupLayout borsaBilgiPanelLayout = new javax.swing.GroupLayout(borsaBilgiPanel);
        borsaBilgiPanel.setLayout(borsaBilgiPanelLayout);
        borsaBilgiPanelLayout.setHorizontalGroup(
            borsaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borsaBilgiPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(borsaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(borsaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fiyatDegisikligiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fiyatDegisikligiYuzdeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sonFiyatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enDusukFiyatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enYuksekFiyatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hacimLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        borsaBilgiPanelLayout.setVerticalGroup(
            borsaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borsaBilgiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(borsaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fiyatDegisikligiLabel))
                .addGap(18, 18, 18)
                .addGroup(borsaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fiyatDegisikligiYuzdeLabel))
                .addGap(18, 18, 18)
                .addGroup(borsaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sonFiyatLabel))
                .addGap(18, 18, 18)
                .addGroup(borsaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(enDusukFiyatLabel))
                .addGap(18, 18, 18)
                .addGroup(borsaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(enYuksekFiyatLabel))
                .addGap(18, 18, 18)
                .addGroup(borsaBilgiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(hacimLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kriptoParaDurumPanel.add(borsaBilgiPanel);

        paralarListe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                paralarListeItemStateChanged(evt);
            }
        });

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel1.setText("Kripto Para Seç:");

        mumPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mum Grafiği", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        javax.swing.GroupLayout mumPanelLayout = new javax.swing.GroupLayout(mumPanel);
        mumPanel.setLayout(mumPanelLayout);
        mumPanelLayout.setHorizontalGroup(
            mumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        mumPanelLayout.setVerticalGroup(
            mumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        durumLabel.setFont(durumLabel.getFont().deriveFont(durumLabel.getFont().getStyle() | java.awt.Font.BOLD));
        durumLabel.setForeground(new java.awt.Color(235, 23, 23));
        durumLabel.setText("Borsa Yükleniyor. Lütfen Bekleyin!");

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel2.setText("Borsa Durumu:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paralarListe, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(durumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(mumPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kriptoParaDurumPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paralarListe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(durumLabel)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kriptoParaDurumPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mumPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paralarListeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_paralarListeItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            KriptoPara para=(KriptoPara)paralarListe.getSelectedItem();
            try {
              KriptoParaBorsaBilgi kpbs=hdc.kriptoParaBorsaBilgiGetir(para.getSymbol());
              fiyatDegisikligiLabel.setText(kpbs.getPriceChange());
              fiyatDegisikligiYuzdeLabel.setText("%"+kpbs.getPriceChangePercent());
              sonFiyatLabel.setText(kpbs.getLastPrice());
              enDusukFiyatLabel.setText(kpbs.getLowPrice());
              enYuksekFiyatLabel.setText(kpbs.getHighPrice());
              hacimLabel.setText(kpbs.getVolume()+ " BTC");
              mgy.mumGuncelle(para.getSymbol());
             
            } catch (Exception ex) {
            }
            sembolIconLabel.setIcon(para.getParaResmi());
            sembolMetinLabel.setText(para.getBaseAsset());
       }
    }//GEN-LAST:event_paralarListeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KriptoParaDurumuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KriptoParaDurumuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KriptoParaDurumuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KriptoParaDurumuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KriptoParaDurumuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel borsaBilgiPanel;
    private javax.swing.JLabel durumLabel;
    private javax.swing.JLabel enDusukFiyatLabel;
    private javax.swing.JLabel enYuksekFiyatLabel;
    private javax.swing.JLabel fiyatDegisikligiLabel;
    private javax.swing.JLabel fiyatDegisikligiYuzdeLabel;
    private javax.swing.JLabel hacimLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel kriptoParaDurumPanel;
    private javax.swing.JPanel mumPanel;
    private javax.swing.JComboBox<String> paralarListe;
    private javax.swing.JLabel sembolIconLabel;
    private javax.swing.JLabel sembolMetinLabel;
    private javax.swing.JPanel sembolPanel;
    private javax.swing.JLabel sonFiyatLabel;
    // End of variables declaration//GEN-END:variables
}
